# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42bb8a5893b3b997f923d92ca5fca7f5d84879ee0f69e70ebc5928ea78592e0a32c19d68b30c73fc144812bd87d1073b03d18c06f8e6a7a92bd970edb0ccbe59

test:
  secret_key_base: 5eeeced5aa9054d9ed9c0130db9fa29aef2b47279b4008f49247ba65d35bfc811d5bdcaa7f72dd1b6e3a56313c413995328551666592c72925aacea731c012b6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
